#!/bin/sh
execute -clrf 'DISPLAY=:0.0 /central/java/jdk1.6.0/bin/java -Xms512M -Xmx1248M -Djava.library.path=/central/home/demo/.jnilib -Djreality.config='$PWD'/portal.$HOSTNAME -Djreality.jogl.quadBufferedStereo=true -jar '$PWD'/../lib/smrj-client.jar'
