#!/bin/sh
execute -clrf 'DISPLAY=:0.0 /central/java/jdk1.5.0_06/bin/java -Xms512M -Xmx1248M -Djreality.config='$PWD'/portal.$HOSTNAME -Djreality.jogl.quadBufferedStereo=true -jar '$PWD'/../lib/smrj-client.jar'
