#!/bin/bash

JR=/Users/weissman/Development/jreality_ws/jreality
ARGS="-Xms256M -Xmx396M -Djava.library.path=$JR/jni/macosx"

java -Djreality.config=demo.left $ARGS -jar ../lib/smrj-client.jar &
java -Djreality.config=demo.center $ARGS -jar ../lib/smrj-client.jar &
java -Djreality.config=demo.right $ARGS -jar ../lib/smrj-client.jar &
java -Djreality.config=demo.floor $ARGS -jar ../lib/smrj-client.jar &


#
# to test the cave rendering on 4 walls
# run JRViewer or tutorials with the following vm arguments:
#
# -Dde.jreality.scene.Viewer=de.jreality.portal.PortalServerViewer
# -Dde.jreality.viewerapp.env=portal
# -Dde.jreality.portal.localViewer=de.jreality.jogl.Viewer
#
